name: Docs

on:
  push:
    branches: [main, GRIDEDIT-358_docs]

jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -e .[dev]
          pip install sphinx

      - name: Run sphinx
        run: make html
        working-directory: docs

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
