name: Sonar Cloud

on:
  push:
    branches: [main]
  pull_request:

jobs:

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install MeshKernelPy
      run: |
        pip install -e ".[dev]"

    - name: Run tests and code coverage
      run: |
        pytest --cov=meshkernel --cov-report=xml

    - name: SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
